webtalk_init -webtalk_dir D:/GitHub/sutech-fpga-1402/WSystemVivado/WSystemVivado.sim/sim_1/behav/xsim/xsim.dir/TB_WSystem_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jul  5 09:35:45 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dc9d1915-e828-4b03-bfe9-2f9710ec4f78" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "068954f17905491ebb855f6da9ed24a2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A8-7410 APU with AMD Radeon R5 Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2196 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6388_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4195625234 -regid "" -xml D:/GitHub/sutech-fpga-1402/WSystemVivado/WSystemVivado.sim/sim_1/behav/xsim/xsim.dir/TB_WSystem_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/GitHub/sutech-fpga-1402/WSystemVivado/WSystemVivado.sim/sim_1/behav/xsim/xsim.dir/TB_WSystem_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/GitHub/sutech-fpga-1402/WSystemVivado/WSystemVivado.sim/sim_1/behav/xsim/xsim.dir/TB_WSystem_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
